### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by cesartecnicas** [Majoras-Mask/template-tp-grupalGrupo02#1]
Tienen que definir cual va a ser su workflow en Git. Pueden dejarlo especificado en una página de la Wiki.

https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by Nimble-Momonga** [comment]
Definido por el equipo y anotado en la wiki, workflow a usar: feature branch
