### ISSUE TITLE
Diagrama de secuencia de los procesos principales

### ISSUE THREAD

**Issue by Flotristant** [Majoras-Mask/template-tp-grupalGrupo02#19]
Agreguen en la wiki, en la vista de procesos, los diagramas de secuencia que expliquen la interacción de los distintos objetos para los siguientes casos:
- Pick element
- Ingresar un comando no permitido
- Look around
- What can i do with <un elemento>?

**Comment by fcancel** [comment]
Agregado:
https://github.com/Majoras-Mask/template-tp-grupalGrupo02/wiki/Process-View2
