### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by Flotristant** [Majoras-Mask/template-tp-grupalGrupo02#23]
Explicar por qué usaron este patrón. Ventajas y Desventajas.

**Comment by fcancel** [comment]
Agregado explicación:
https://github.com/Majoras-Mask/template-tp-grupalGrupo02/wiki/Patrones

**Comment by Flotristant** [comment]
Chicos, conozco las ventajas y desventajas de los patrones en sí. Se les pidió que expliquen las ventajas y desventajas de estos patrones en su diseño..
