### ISSUE TITLE
Dividir el diagrama de clases de forma de que acompañe la explicación

### ISSUE THREAD

**Issue by Flotristant** [Majoras-Mask/template-tp-grupalGrupo02#24]
En la vista lógica, junto con la explicación del uso de los patrones, incluir el diagrama de clases que acompaña a la explicación de forma de poder visualizar el diseño que se está explicando.

**Comment by fcancel** [comment]
Agregado:
https://github.com/Majoras-Mask/template-tp-grupalGrupo02/wiki/Logical-view2
