### ISSUE TITLE
Enumerar los cambios que tuvieron que realizar en la iteración 2 para agregar las nuevas funcionalidades

### ISSUE THREAD

**Issue by Flotristant** [Majoras-Mask/template-tp-grupalGrupo02#25]

**Comment by fcancel** [comment]
Enumerado los cambios realizados:
https://github.com/Majoras-Mask/template-tp-grupalGrupo02/wiki/Iteraci%C3%B3n-2,-impacto-sobre-el-motor-de-juegos
