### ISSUE TITLE
Compatibilidad con jar

### ISSUE THREAD

**Issue by Flotristant** [Majoras-Mask/template-tp-grupalGrupo02#26]
En la entrega pasada, no utilizaron el jar para cargar el juego en el engine. Para la próxima entrega, el engine tiene que cargar el juego desde un jar como se pidió para la iteración anterior.

**Comment by fcancel** [comment]
Nuevo branch idea contempla el uso de archivos *.jar cargados mediante la función provista por el template-tp-grupalGrupo02 original

**Comment by Flotristant** [comment]
¿Qué branch? ¿Está integrado?
