### ISSUE TITLE
Revisar la vista fisica

### ISSUE THREAD

**Issue by Flotristant** [Majoras-Mask/template-tp-grupalGrupo02#29]
Esta descripción:

https://github.com/Majoras-Mask/template-tp-grupalGrupo02/wiki/Vista-f%C3%ADsica-iteraci%C3%B3n-3

No muestra al cliente, en su lugar aparece el game. Sin embargo este cambio no figura en la explicación de la iteración 3.
Revisen.

**Comment by fcancel** [comment]
Cambios realizados a la vista física:
https://github.com/Majoras-Mask/template-tp-grupalGrupo02/wiki/Vista-f%C3%ADsica-iteraci%C3%B3n-3
