### ISSUE TITLE
Bug al cargar el jar

### ISSUE THREAD

**Issue by Flotristant** [Majoras-Mask/template-tp-grupalGrupo02#30]
![captura de pantalla de 2016-06-16 09 55 14](https://cloud.githubusercontent.com/assets/4529904/16117522/f3950346-33a8-11e6-801a-ef282a727231.png)

Chicos, **le estan pasando como path el comando completo**, en la screenshot lo pueden ver. 
Corrijan esto, agreguen el driver y armen tests que prueben el funcionamiento.

**Comment by fcancel** [comment]
Solved in commit  0b61fd3
