### ISSUE TITLE
BUG: Comportamiento raro de los commands

### ISSUE THREAD

**Issue by Flotristant** [Majoras-Mask/template-tp-grupalGrupo02#31]
Le pasé el mismo comando varias veces al servidor y responde diferente según qué comando respondió anteriormente.

> Connected to the target VM, address: '127.0.0.1:35027', transport: 'socket'
> Server> Welcome to Majora's Mask game service, type 'help' to know the commands
> load game "/home/florencia/test/GameBuilderSePierdeALos30Segs.jar"
> Server> **Unknown command, try with 'help'**
> load game
> Server> **Please provide a path to a game Jar.**
> load game "/home/florencia/test/GameBuilderSePierdeALos30Segs.jar"
> Server> **No class found with that name.**
> load game "/home/florencia/test/GameBuilderSePierdeALos30Segs.jar"
> Server> **Unknown command, try with 'help'**

También vi esto:

 **Server> Unknown command, try with 'help'
load game
Server> Please provide a path to a game Jar.
load game
Server> No class found with that name.**

**Comment by addinkevin** [comment]
Esto se debe a la forma en la que trabaja el comando load game. Luego de ejecutar load game, se debe especificar el jar correspondiente. Documentado en la wiki y el readme de master.
