### ISSUE TITLE
BUG : el segundo player no tiene nombre

### ISSUE THREAD

**Issue by Flotristant** [Majoras-Mask/template-tp-grupalGrupo02#32]
**Client> Welcome to the client!!
connect 127.0.0.1:8000
Client> Welcome to the game, you are**

**Comment by addinkevin** [comment]
Esto se debe a que el juego ya no tiene mas jugadores disponibles. Se agrego un chequeo en el servidor para que rechace al cliente dado y no se le permita la conexión.
